# Python for Data Science  (Practice-1)

## Python Types

In [9]:
type(11)

str

In [10]:
type(21.25)

float

In [11]:
type("Python for Data Basics")

str

In [12]:
int(1.1)

1

In [13]:
int('A')
# Not Valid

ValueError: invalid literal for int() with base 10: 'A'

In [14]:
float('11')

11.0

In [15]:
int(3.99)

3

In [16]:
str(1)

'1'

In [17]:
type(True)
# Boolean

bool

In [18]:
int(True)

1

In [20]:
float(True)

1.0

## ExpressionS and Variables

In [21]:
40+65+52+89

246

In [22]:
50-60

-10

In [23]:
25/5

5.0

In [24]:
25/6

4.166666666666667

In [25]:
25//6

4

In [26]:
30+2*60

150

In [27]:
(30+2)*60

1920

In [31]:
a = 1

In [30]:
a

1

In [37]:
a = 40+25+65+32
a

162

In [39]:
b=a/3
b

54.0

In [40]:
type(b)

float

In [43]:
3+2*2

7

## String Operations

In [63]:
Name = "Charan Reddy "
Name

'Charan Reddy '

In [64]:
Name[3]

'r'

In [72]:
Name[-1]

' '

In [66]:
f_Name = Name[0:6] #Name[0:6:1]
f_Name

'Charan'

In [67]:
l_Name = Name[7::] #Name[7:12:1]
l_Name

'Reddy '

In [68]:
ran = Name[0::2] #Here 2 represents the skip order
ran

'Caa ed '

In [69]:
len(Name)

13

In [70]:
Name_2 = Name + " N S"
Name_2

'Charan Reddy  N S'

In [71]:
Name_3 = 3 * Name
Name_3

'Charan Reddy Charan Reddy Charan Reddy '

In [75]:
print("Charan Ns is a good boy.\nHe is in LPU.")

Charan Ns is a good boy.
He is in LPU.


In [77]:
print("Charan Ns is a good boy.\\ He is in LPU.")

Charan Ns is a good boy.\ He is in LPU.


In [78]:
print(r"Charan Ns is a good boy.\ He is in LPU.")

Charan Ns is a good boy.\ He is in LPU.


## String Methods

In [80]:
A = "Thriller is the sixth studio album"
B = A.upper()
B

'THRILLER IS THE SIXTH STUDIO ALBUM'

In [81]:
c = A.replace('Thriller','Tseries')
c

'Tseries is the sixth studio album'

In [82]:
Name.find('ar') # "Charan".find("ar")

2

## Tuples 
#### Imutable
Ordered Sequence

In [113]:
Ratings = (10,9,5,8,4,5,6,9)
Ratings

(10, 9, 5, 8, 4, 5, 6, 9)

In [114]:
tup = ('disco',10,12.5)
tup

('disco', 10, 12.5)

In [115]:
tup[0]

'disco'

In [116]:
tup[-3]

'disco'

In [117]:
tup1 = Ratings + tup
tup1

(10, 9, 5, 8, 4, 5, 6, 9, 'disco', 10, 12.5)

In [118]:
len(tup1)

11

In [119]:
RatingSort = sorted(Ratings)
RatingSort

[4, 5, 5, 6, 8, 9, 9, 10]

In [120]:
NT = (1,2,("pop","rock"),(3,4),("disco",(1,2)))
NT

(1, 2, ('pop', 'rock'), (3, 4), ('disco', (1, 2)))

In [121]:
NT[2][1]

'rock'

## Lists
#### Mutable

In [122]:
L = ["Charan Reddy",10.1,1982]
L

['Charan Reddy', 10.1, 1982]

In [123]:
B=[1,2,[3,'a'],[4,'b']]
B

[1, 2, [3, 'a'], [4, 'b']]

In [124]:
B[3][1]

'b'

In [125]:
L1 = L + B
L1

['Charan Reddy', 10.1, 1982, 1, 2, [3, 'a'], [4, 'b']]

In [126]:
L1.extend(["CR",12])
L1

['Charan Reddy', 10.1, 1982, 1, 2, [3, 'a'], [4, 'b'], 'CR', 12]

In [127]:
L1.append(["CR",12])
L1

['Charan Reddy', 10.1, 1982, 1, 2, [3, 'a'], [4, 'b'], 'CR', 12, ['CR', 12]]

In [129]:
L1[0] = 'CR'
L1

['CR', 10.1, 1982, 1, 2, [3, 'a'], [4, 'b'], 'CR', 12, ['CR', 12]]

In [130]:
del(L1[0])
L1

[10.1, 1982, 1, 2, [3, 'a'], [4, 'b'], 'CR', 12, ['CR', 12]]

In [131]:
"Hello Mike".split()  # Converting string to list

['Hello', 'Mike']

In [132]:
"A,B,C,D".split(",")  # Splitting in to lists using delimiter

['A', 'B', 'C', 'D']

In [134]:
# Cloning of a list

L2 = L1[:]
L2

[10.1, 1982, 1, 2, [3, 'a'], [4, 'b'], 'CR', 12, ['CR', 12]]

In [135]:
len(("disco",10,1.2, "hard rock",10))

5

## Dictionaries

In [136]:
{"a":1,"b":2}
# Here a,b are keys and 1,2 are values

{'a': 1, 'b': 2}

In [137]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}
Dict["D"]

(4, 4, 4)

In [139]:
Dict.keys()  # Displays all keys

dict_keys(['A', 'B', 'C', 'D', 'E', 'F'])

In [140]:
Dict.values()  # Displays all values

dict_values([1, '2', [3, 3, 3], (4, 4, 4), 5, 6])

## Sets
It containS only unique items.

In [143]:
s = {'a','a','b','c','d','f','a','f','b','c','d','e'}
s

{'a', 'b', 'c', 'd', 'e', 'f'}

In [144]:
# We can convert list to set
type(set([1,2,3]))

set

### Set Operations

In [148]:
A = {'Thriller','Back in Black','AC','DC'}
A

{'AC', 'Back in Black', 'DC', 'Thriller'}

In [152]:
A.add('NSYNC')
A

{'AC', 'Back in Black', 'DC', 'NSYNC', 'Thriller'}

In [153]:
A.remove('NSYNC')
A

{'AC', 'Back in Black', 'DC', 'Thriller'}

In [154]:
'NSYNC' in A

False

In [155]:
'AC' in A

True

In [161]:
B = {'Thriller','Back in Black','AC'}
C = {'Thriller','AC','DC'}
D = B & C
D

{'AC', 'Thriller'}

In [162]:
B.union(C)

{'AC', 'Back in Black', 'DC', 'Thriller'}

In [163]:
D.issubset(B)

True

## Conditioning and Branching

In [166]:
a = 6
a == 7

False

In [168]:
6 == 6

True

In [170]:
i = 2
i < 5

True

In [172]:
i!=3

True

In [173]:
5!=5

False

In [174]:
"Charan"!="Reddy"

True

In [175]:
"Charan"=="Reddy"

False

In [176]:
'a'=='A'

False

In [179]:
age = 15
if (age > 18):
    print("You can Enter")
print("Move on") #This statement is out of if so it's not effected with the conditionn

Move on


In [180]:
age = 15
if (age > 18):
    print("You can Enter")
else:
    print("Go to Meat Loaf")
print("Move on")

Go to Meat Loaf
Move on


In [183]:
age = 18
if (age > 18):
    print("You can Enter")
elif (age == 18):
    print("Go to Pink Floyd")
else:
    print("Go to Meat Loaf")
print("Move on")

Go to Pink Floyd
Move on


#### Logical Operators

In [185]:
not(True)

False

In [186]:
A = True
B = False
C = A or B
C

True

In [187]:
C = A and B
C

False

## Loops

In [189]:
range(3)

range(0, 3)

In [190]:
range(10,15)

range(10, 15)

In [192]:
squares = ['red','yellow','green','purple','blue']

In [193]:
for i in range(0,5):
    squares[i]='White'
squares

['White', 'White', 'White', 'White', 'White']

In [194]:
for x in ['A','B','C']:
  print(x+'A')

AA
BA
CA


In [195]:
for i,x in enumerate(['A','B','C']):
    print(i,x)

0 A
1 B
2 C


In [196]:
squares = ['red','red','green','red','blue']
Newsquares = []
i = 0
while(squares[i]=='red'):
    Newsquares.append(squares[i])
    i=i+1
Newsquares

['red', 'red']

In [200]:
for i in range(1,5):
    if (i!=2):
        print(i)

1
3
4


## Functions

Built-in

In [201]:
len(['A','B',1])

3

In [203]:
sum([5,2,0,8])

15

Sorted VS Sort

In [204]:
L=[1,3,2]
sorted(L)
L

[1, 3, 2]

In [208]:
L.sort()
L

[1, 2, 3]

In [209]:
sorted(L) 
#In sorted there will be no change in the original as it creates new sorted array whereas in sort it sorts the original array.

[1, 2, 3]

User defined functions

In [215]:
a = 5
def add1(a):
    b=a+1
    return b
add1(a)

6

In [217]:
c = add1(10)
c

11

In [219]:
c=add1(2)
c=add1(10)
c

11

In [221]:
# Documentation for a function

def add1(a):
    """
    add 1 to a
    """
    b=a+1
    return b

help(add1)

Help on function add1 in module __main__:

add1(a)
    add 1 to a



In [223]:
def NoWork():
    pass
print(NoWork())

None


In [226]:
def Print(A):
    for a in A:
        print(a+'1')
        
Print(['a','b','c'])

a1
b1
c1


In [229]:
# Declaring a global variable
def PinkFloyd():
    global ClaimedSales
    ClaimedSales = '45 Million'
    return ClaimedSales
PinkFloyd()
# print(ClaimedSales)

'45 Million'

In [230]:
print(ClaimedSales)

45 Million


In [235]:
a=1

def do(x):
    a=100
    return(x+a)

print(do(1))


101


## Objects and Classes

In [241]:
class Circle(object):
    def __init__(self,radius,color):
        
        self.radius = radius;
        self.color = color;
        
class Rectangle(object):
    def _init_(self,color,height,width):
        self.height = height
        self.width = width
        self.color = color

In [244]:
RedCircle = Circle(10,'red')
C1 = Circle(10,'red')
Circle(3,'blue')

TypeError: Circle() takes no arguments

In [245]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points(1,2)
p1.print_point()

x= 1  y= 2


In [246]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2


## Reading files with open

In [18]:
with open("Example.txt","r") as File1:    
     file_stuff=File1.readline ()    # This reads only one line in the file I.e line 1
     file_stuff=File1.readline ()    # For the second time it reads 2nd line and so on . .
     


TypeError: 'file_stuff' is an invalid keyword argument for print()

## Writing Files with Open

In [17]:
with open("Example.txt","a") as writefile:
  writefile.write("This is line A\n")
  writefile.write("This is line B\n")

## Loading Data with Pandas

In [19]:
import pandas


## 1-D Numpy

In [23]:
import numpy as np

a = np.array([0,1,2,3,4])
a[0]

0

In [24]:
type(a)

numpy.ndarray

In [26]:
a.dtype

dtype('int32')

In [27]:
a.size

5

In [28]:
a.ndim

1

In [29]:
a.shape

(5,)

In [30]:
b = np.array([2.21,1.23,25.36,12.3,3.25])
type(b)

numpy.ndarray

In [31]:
b.dtype

dtype('float64')

In [32]:
b[0]=100
b

array([100.  ,   1.23,  25.36,  12.3 ,   3.25])

In [33]:
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
a*b

array([2, 2, 2, 2, 2])

In [34]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [35]:
a=np.array([1,1,1,1,1])
a+10 

array([11, 11, 11, 11, 11])

## 2-D Numpy

In [37]:
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [38]:
A.ndim

2

In [39]:
A.shape

(3, 3)

In [40]:
A.size

9

In [41]:
A[0:2,2]

array([13, 23])

In [44]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [45]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [46]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])